# Generated by Django 5.0.4 on 2024-04-06 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nombre_cliente', models.CharField(max_length=120)),
                ('email_cliente', models.EmailField(max_length=254, unique=True)),
                ('locacion', models.CharField(max_length=120)),
                ('ciudad', models.CharField(max_length=120)),
                ('pais', models.CharField(max_length=120)),
            ],
        ),
    ]
